# Generated by Django 2.1.7 on 2019-06-01 21:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('unread', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=210, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('L', 'liked'), ('C', 'commented'), ('S', 'shared'), ('A', 'answered'), ('F', 'following'), ('P', 'posted')], max_length=1)),
                ('subject_object_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-time',),
            },
        ),
    ]
