# Generated by Django 2.1.7 on 2019-07-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190705_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_object_id',
            field=models.CharField(max_length=40),
        ),
    ]
