# Generated by Django 2.1.7 on 2019-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190617_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('L', 'liked'), ('C', 'commented'), ('S', 'shared'), ('A', 'answered'), ('F', 'following'), ('P', 'posted'), ('R', 'replied')], max_length=1),
        ),
    ]
