# Generated by Django 2.1.7 on 2019-06-01 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('released_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)])),
                ('country', models.CharField(max_length=40)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies_director', to='persons.Star')),
                ('genre', models.ManyToManyField(related_name='movies_genre', to='movies.Genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies_language', to='movies.Language')),
                ('stars', models.ManyToManyField(to='persons.Star')),
                ('writers', models.ManyToManyField(related_name='movies_writer', to='persons.Star')),
            ],
        ),
    ]
