# Generated by Django 2.1.7 on 2019-07-05 13:33

from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_of_group', models.CharField(choices=[('C', 'Closed'), ('O', 'Open')], default='O', max_length=1)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBlog',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('watched', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('contents', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/%(class)/%Y/%m/%d')),
                ('heading', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
