# Generated by Django 2.1.7 on 2019-06-18 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190617_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupblog',
            name='uuid_ui',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
