# Generated by Django 2.1.7 on 2019-06-27 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupblog_uuid_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='groups_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
