# Generated by Django 2.1.7 on 2019-07-05 13:33

from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('watched', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('contents', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/%(class)/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('watched', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('contents', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/%(class)/%Y/%m/%d')),
                ('heading', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('watched', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('contents', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/%(class)/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('spoiler_alert', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('add_content', models.TextField()),
                ('action', models.CharField(choices=[('W', 'Watching'), ('F', 'Feeling')], max_length=1)),
                ('image', models.ImageField(null=True, upload_to='status_images/%Y/%m/%d/')),
            ],
        ),
    ]
