# Generated by Django 2.2.4 on 2019-08-14 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20190705_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='add_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
