# Generated by Django 2.2.4 on 2019-08-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20190814_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='add_content',
            new_name='content',
        ),
    ]
