version: '3'
services: 
  web:
    build: . 
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 127.0.0.1:${APP_PORT}" 
    volumes:
      - .:/microservice
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    image: microservice_app 
    expose: 
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}

    restart: "on-failure"

    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGPORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}

    restart: "on-failure"

volumes:
  postgres_data:
    driver: local