# Generated by Django 2.1.7 on 2019-06-27 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='followers',
            field=models.ManyToManyField(related_query_name='following_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
