# Generated by Django 2.1.7 on 2019-07-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='followers',
            field=models.ManyToManyField(related_name='following_stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='star',
            name='social_media',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='star', to='persons.SocialMedia'),
        ),
    ]
