# Generated by Django 2.2.8 on 2020-04-14 17:55

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.CharField(blank=True, max_length=40, null=True)),
                ('response',
                 models.CharField(choices=[('T', 'Thanks'), ('A', 'You are late.'), ('C', 'Bad choice.')], max_length=1,
                                  null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.ContentType')),
            ],
        ),
    ]
