# Generated by Django 2.2.8 on 2020-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('suggestions', '0002_auto_20200414_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='response',
            field=models.CharField(blank=True, choices=[('T', 'Thanks'), ('A', 'You are late.'), ('C', 'Bad choice.')],
                                   max_length=1, null=True),
        ),
    ]
