# Generated by Django 2.2.8 on 2021-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('suggestions', '0002_auto_20200913_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
