# Generated by Django 2.1.7 on 2019-06-17 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('no_of_watches', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
