# Generated by Django 2.1.7 on 2019-06-27 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20190617_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'time', 'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(related_name='topics_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
