# Generated by Django 2.1.7 on 2019-06-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20190602_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-time',)},
        ),
    ]
