# Generated by Django 2.1.7 on 2019-06-27 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20190628_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='topics_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
