# Generated by Django 2.1.7 on 2019-06-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20190617_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggest_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggest_content_object_id',
            new_name='object_id',
        ),
    ]
