# Generated by Django 2.1.7 on 2019-07-05 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, default='', upload_to='')),
                ('biography', models.TextField()),
            ],
        ),
    ]
