# Generated by Django 2.2.8 on 2020-04-14 17:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, default='', upload_to='')),
                ('biography', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
