# Generated by Django 2.2.8 on 2020-04-14 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stars',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='star',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='star',
            name='social_media',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='star',
                                       to='persons.SocialMedia'),
        ),
        migrations.AddField(
            model_name='star',
            name='updated_by',
            field=models.ManyToManyField(related_name='updated_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
