# Generated by Django 2.2.8 on 2020-05-31 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0002_auto_20200414_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='star',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='updated_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
