# Generated by Django 2.2.4 on 2019-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190705_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
