# Generated by Django 2.2.8 on 2020-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persons', '0003_auto_20200531_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
