# Generated by Django 2.2.8 on 2020-09-13 14:23

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='authorizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='authorized_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupblog',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='groupblog_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupblog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs',
                                    to='groups.Group'),
        ),
        migrations.AddField(
            model_name='groupblog',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='groupblog_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupblog',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='groupblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='groups_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClosedGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('groups.group',),
        ),
        migrations.CreateModel(
            name='ClosedGroupBlog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('groups.groupblog',),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests',
                                    to='groups.ClosedGroup'),
        ),
    ]
