# Generated by Django 2.1.7 on 2019-06-03 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_auto_20190602_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='disliked',
            field=models.ManyToManyField(related_name='blog_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.ManyToManyField(related_name='blog_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='disliked',
            field=models.ManyToManyField(related_name='review_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.ManyToManyField(related_name='review_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
