# Generated by Django 2.1.7 on 2019-06-06 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0004_auto_20190603_1718'),
        ('contents', '0005_auto_20190603_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('contents', models.TextField()),
                ('watched', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('disliked', models.ManyToManyField(related_name='answer_disliked', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(related_name='answer_liked', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
