# Generated by Django 2.2.8 on 2020-09-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persons', '0002_auto_20200913_1953'),
        ('movies', '0002_auto_20200913_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='movies_director', to='persons.Star'),
        ),
    ]
