# Generated by Django 2.2.8 on 2021-02-26 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persons', '0002_auto_20200913_1953'),
        ('movies', '0003_auto_20200913_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies_directors', to='persons.Star'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900),
                                                             django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
