# Generated by Django 2.2.8 on 2020-05-05 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0003_auto_20200414_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='created_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='movies_director', to='persons.Star'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='movies_language', to='movies.Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900),
                                                             django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
