# Generated by Django 2.2.8 on 2020-04-14 17:55

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('unread', models.BooleanField(default=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(
                    choices=[('LK', 'liked'), ('CM', 'commented'), ('SR', 'shared'), ('AN', 'answered'),
                             ('FL', 'following'), ('PT', 'posted'), ('RP', 'replied'), ('SG', 'suggestion'),
                             ('JR', 'group join'), ('RA', 'request approved')], max_length=2)),
                ('subject_object_id', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-time',),
            },
        ),
    ]
