# Generated by Django 2.2.8 on 2020-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0002_auto_20200414_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LK', 'likes'), ('CM', 'commented'), ('SR', 'shared'), ('AN', 'answered'),
                                            ('FL', 'following'), ('PT', 'posted'), ('RP', 'replied'),
                                            ('SG', 'suggestion'), ('JR', 'group join'), ('RA', 'request approved')],
                                   max_length=2),
        ),
    ]
